apiVersion: v1
kind: Secret

metadata:
  name: mongo-secret

type: Opaque # Opaque is default type, it use key-value pair.

# value must be in base64
# to convert to base64 use "echo -n 'admin' | base64"
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: YWRtaW4=