apiVersion: v1
kind: Service

metadata:
  name: mongo-internal-svc

spec:
  selector:
    app: mongodb #It will decide, connect service to which pod.
  ports:
    - protocol: TCP
      port: 27017 #service port
      targetPort: 27017 #container port