apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-mongo-deploy
  labels:
    app: web-mongo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-mongo
  template:
    metadata:
      labels:
        app: web-mongo
    spec:
      containers:
      - name: web-mongo
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: web-mongo-config
              key: database_url

